version: 2
jobs:
  build:
    working_directory: "~/circle-ci"
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm test
