version: 2
jobs:
  build:
    working_directory: "/home/ghost/Dev/Sandbox/ci/circle-ci"
    docker:
      - image: circle/node:7
    steps:
      - checkout
      - run: npm install
      - run: npm test
